version: '3.1'
services:
  stats-server:
    build:
      context: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

  ewm-service:
    build:
      context: ./ewm/ewm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm

volumes:
  stats-db-data:
  ewm-db-data:
