server:
  port: 8080
  url: ${SERVER_URL:http://localhost:9090}

spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
      properties:
        hibernate:
          format_sql: true
          dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQL10Dialect}

  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6543/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}

---
spring:
  config:
    activate:
      on-profile: ci, test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test